### ISSUE TITLE
如何评价MelonCmd

### ISSUE THREAD

**Issue by singer01** [GoogolOwO/classed-bbcode#2]

**Comment by GoogolOwO** [comment]
是暴政者，但是请勿打开离题issue，谢谢。

**Comment by singer01** [comment]
> 是暴政者，但是请勿打开离题issue，谢谢。
就开这一个

**Comment by GoogolOwO** [comment]
我有必要提醒你，发布离题issue可能导致您被GitHub flagged

**Comment by singer01** [comment]
> 我有必要提醒你，发布离题issue可能导致您被GitHub flagged

无所谓，这个号也快没了，你支持改革开放吗

**Comment by GoogolOwO** [comment]
https://docs.github.com/zh/site-policy/acceptable-use-policies/github-acceptable-use-policies

**Comment by singer01** [comment]
> https://docs.github.com/zh/site-policy/acceptable-use-policies/github-acceptable-use-policies

逆天

**Comment by singer01** [comment]
> https://docs.github.com/zh/site-policy/acceptable-use-policies/github-acceptable-use-policies

打倒一切走资派

**Comment by singer01** [comment]
> https://docs.github.com/zh/site-policy/acceptable-use-policies/github-acceptable-use-policies

打倒一切走资派

**Comment by cmd1152** [comment]
@singer01 不是哥们，我看你搁这骚扰用户骚扰很久了啊
